diff --git a/Makefile b/Makefile
index cf3412d..b11db66 100644
--- a/Makefile
+++ b/Makefile
@@ -1,7 +1,7 @@
 VERSION = 3
 PATCHLEVEL = 15
 SUBLEVEL = 0
-EXTRAVERSION = -rc7
+EXTRAVERSION = -eudyptula
 NAME = Shuffling Zombie Juror
 
 # *DOCUMENTATION*
